export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: "Invalid credentials.",
  USER_ALREADY_EXISTS: "User already exists.",
  ROLE_NOT_FOUND: "Role not found",
  ASSIGN_ROLE_ERROR: "Error assigning role.",
  SIGNUP_FAILED: "Signup failed.",
  LOGIN_FAILED: "Login failed.",
  GOOGLE_SIGNIN_FAILED: "Google sign-in failed.",
  MISSING_GOOGLE_DATA: "Missing Google user data.",
  PROVIDER_NOT_ALLOWED: "Provider is not allowed.",
  PRODUCT_NOT_FOUND: "Product not found.",
  PRODUCT_RETRIEVE_FAILED: "Failed to retrieve product(s).",
  PRODUCT_CREATE_FAILED: "Failed to create product.",
  PRODUCT_UPDATE_FAILED: "Failed to update product.",
  PRODUCT_DELETE_FAILED: "Failed to delete product.",
  CLIENT_NOT_FOUND: "Client not found",
  USER_NOT_FOUND: "User not found",
  CANNOT_DELETE_USER_WITH_CLIENTS: "Cannot delete user with associated clients",
  USER_DELETE_FAILED: "Failed to delete user"
};
