export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: "Invalid credentials.",
  USER_ALREADY_EXISTS: "User already exists.",
  ROLE_NOT_FOUND: "Role not found",
  ASSIGN_ROLE_ERROR: "Error assigning role.",
  SIGNUP_FAILED: "Signup failed.",
  LOGIN_FAILED: "Login failed.",
  GOOGLE_SIGNIN_FAILED: "Google sign-in failed.",
  MISSING_GOOGLE_DATA: "Missing Google user data.",
  PROVIDER_NOT_ALLOWED: "Provider is not allowed.",
  PRODUCT_NOT_FOUND: "Product not found.",
  PRODUCT_RETRIEVE_FAILED: "Failed to retrieve product(s).",
  PRODUCT_CREATE_FAILED: "Failed to create product.",
  PRODUCT_UPDATE_FAILED: "Failed to update product.",
  PRODUCT_DELETE_FAILED: "Failed to delete product.",
  CLIENT_NOT_FOUND: "Client not found",
  USER_NOT_FOUND: "User not found",
  CANNOT_DELETE_USER_WITH_CLIENTS: "Cannot delete user with associated clients",
  USER_DELETE_FAILED: "Failed to delete user",
  USER_EMAIL_EXISTS: "A user with this email already exists",
  TOKEN_EXPIRED: "Token has expired",
  INVALID_TOKEN: "Invalid token",
  NO_TOKEN: "No token provided",
  GENERAL_ERROR: "An error occurred. Please try again later.",
  INVALID_PRODUCT_DATA: "Invalid product data returned from service",
  PRODUCT_RETRIEVE_ALL_FAILED: "Failed to retrieve products",
  PRODUCT_CLIENT_IDS_REQUIRED: "Product ID and Client ID are required",
  PRODUCT_ADD_CLIENT_FAILED: "Failed to add client to product",
  CLIENT_CREATE_FAILED: "Failed to create client",
  UNEXPECTED_ERROR: "An unexpected error occurred.",
  USER_ID_REQUIRED: "User ID is required.",
  CLIENT_NOT_FOUND_FOR_USER: "Client not found for user.",
  FAILED_TO_RETRIEVE_PRODUCTS_FOR_CLIENT: "Failed to retrieve products for client.",
  FAILED_TO_RETRIEVE_PRODUCTS: "Failed to retrieve products.",
  SLACK_NOTIFICATION_FAILED: "Slack notification failed."
};

export const RESPONSE_STATUS = {
  SUCCESS: "success",
  ERROR: "error",
};
