export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: "Invalid credentials.",
  USER_ALREADY_EXISTS: "User already exists.",
  ACCOUNT_DEACTIVATED: "Your account has been deactivated. Please contact support.",
  PASSWORD_CHANGE_REQUIRED: "You must change your password before continuing.",
  ROLE_NOT_FOUND: "Role not found",
  ASSIGN_ROLE_ERROR: "Error assigning role.",
  SIGNUP_FAILED: "Signup failed.",
  LOGIN_FAILED: "Login failed.",
  GOOGLE_SIGNIN_FAILED: "Google sign-in failed.",
  MISSING_GOOGLE_DATA: "Missing Google user data.",
  PROVIDER_NOT_ALLOWED: "Provider is not allowed.",
  PRODUCT_NOT_FOUND: "Product not found.",
  PRODUCT_RETRIEVE_FAILED: "Failed to retrieve product(s).",
  PRODUCT_CREATE_FAILED: "Failed to create product.",
  PRODUCT_UPDATE_FAILED: "Failed to update product.",
  PRODUCT_DELETE_FAILED: "Failed to delete product.",
  CLIENT_NOT_FOUND: "Client not found",
  USER_NOT_FOUND: "User not found",
  CANNOT_DELETE_USER_WITH_CLIENTS: "Cannot delete user with associated clients",
  USER_DELETE_FAILED: "Failed to delete user",
  USER_EMAIL_EXISTS: "A user with this email already exists",
  TOKEN_EXPIRED: "Token has expired",
  INVALID_TOKEN: "Invalid token",
  INVALID_CLIENT_ID: "Invalid Client ID",
  NO_TOKEN: "No token provided",
  FAILED_TO_RESTORE_CLIENT: "Failed to restore client",
  GENERAL_ERROR: "An error occurred. Please try again later.",
  INVALID_PRODUCT_DATA: "Invalid product data returned from service",
  PRODUCT_RETRIEVE_ALL_FAILED: "Failed to retrieve products",
  PRODUCT_CLIENT_IDS_REQUIRED: "Product ID and Client ID are required",
  PRODUCT_ADD_CLIENT_FAILED: "Failed to add client to product",
  CLIENT_CREATE_FAILED: "Failed to create client",
  UNEXPECTED_ERROR: "An unexpected error occurred.",
  USER_ID_REQUIRED: "User ID is required.",
  CLIENT_NOT_FOUND_FOR_USER: "Client not found for user.",
  FAILED_TO_RETRIEVE_PRODUCTS_FOR_CLIENT: "Failed to retrieve products for client.",
  FAILED_TO_RETRIEVE_PRODUCTS: "Failed to retrieve products.",
  SLACK_NOTIFICATION_FAILED: "Slack notification failed.",
  CLIENT_DOES_NOT_EXIST: "Client with id {id} does not exist",
  PRODUCT_DOES_NOT_EXIST: "Product does not exist",
  PRODUCT_NOT_ASSOCIATED_WITH_CLIENT: "Product is not associated with this client",
  NO_CLIENT_ASSOCIATED_WITH_USER: "No client associated with this user",
  USER_DOES_NOT_EXIST: "User does not exist",
  UNAUTHORIZED: "Unauthorized",
  FAILED_TO_RETRIEVE_PRODUCTS_FROM_DATABASE: "Failed to retrieve products from database",
  FAILED_TO_ADD_CLIENT_TO_PRODUCT: "Failed to add client to product",
  FAILED_TO_CREATE_CLIENT: "Failed to create client",
  FAILED_TO_FETCH_CLIENTS: "Failed to fetch clients",
  FAILED_TO_FETCH_CLIENT: "Failed to fetch client",
  CLIENT_NOT_FOUND_UPDATE: "Client not found",
  FAILED_TO_GET_PRODUCTS_FOR_CLIENT: "Failed to get products for client",
  TICKET_NOT_FOUND: "Ticket not found",
  FAILED_TO_RETRIEVE_TICKETS: "Failed to retrieve tickets",
  FAILED_TO_RETRIEVE_TICKET: "Failed to retrieve ticket",
  FAILED_TO_UPDATE_TICKET: "Failed to update ticket",
  FAILED_TO_DELETE_TICKET: "Failed to delete ticket",
  NO_VALID_FIELDS_TO_UPDATE: "No valid fields to update",
  INVALID_PRIORITY: "Invalid priority",
  INVALID_STATUS: "Invalid status",
  CLIENT_CODE_IS_REQUIRED: "Client code is required",
  CLIENT_ID_REQUIRED: "Client ID is required",
  CLIENT_PRODUCT_RELATION_NOT_FOUND: "Client is not linked to this product",
  PRODUCT_REMOVE_CLIENT_FAILED: "Failed to remove client from product",
  FAILED_TO_DELETE_CLIENT: "Failed to soft delete client",
  CLIENT_SOFT_DELETED: "Client is soft deleted and cannot be modified",
  USER_ID_MISSING_IN_REQUEST: "User ID missing in request",
  COMPANY_NAME_REQUIRED: "companyName is required",
  FAILED_TO_FETCH_OVERVIEW_STATS: "Failed to fetch overview statistics",
  FAILED_TO_FETCH_TICKETS_BY_STATUS: "Failed to fetch tickets by status",
  FAILED_TO_FETCH_CLIENT_STATS: "Failed to fetch client statistics",
  FAILED_TO_FETCH_PRODUCT_STATS: "Failed to fetch product statistics",
  FAILED_TO_FETCH_DASHBOARD_DATA: "Failed to fetch dashboard data",
  NOT_AUTHORIZED: "You are not authorized to view this ticket",
  TICKET_TITLE_REQUIRED: "Ticket title is required.",
  TICKET_DESCRIPTION_REQUIRED: "Ticket description is required.",
  TICKET_CLIENT_REQUIRED: "A client must be selected for this ticket.",
};

export const RESPONSE_STATUS = {
  SUCCESS: "success",
  ERROR: "error",
};
